# Generated by Django 4.2.5 on 2023-10-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='populor',
            field=models.BooleanField(default=False),
        ),
    ]
