# Generated by Django 4.2.5 on 2023-10-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_films_populor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=150)),
                ('summary', models.TextField(blank=True, default='', null=True)),
                ('image_url', models.CharField(blank=True, default=False, max_length=3000)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('populor', models.BooleanField(default=False)),
            ],
        ),
    ]
