# Generated by Django 4.2.5 on 2023-10-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_series_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='Type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
