# Generated by Django 4.2.5 on 2023-10-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_films_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=300)),
                ('image_url', models.CharField(blank=True, default=False, max_length=3000)),
            ],
        ),
    ]
